## Function makeCacheMatrix
# This function generates a four element matrix given a matrix as an argument
#
# The named matrix consists of 4 functions 
#  1. matrix$set sets the value of the matrix and Inv to NULL
#  2. matrix$get provides the value of the matrix
#  3. matrix$setInverse sets the function environment value of Inv to the function argument
#  4. matrix$getInverse

makeCacheMatrix <- function(x = matrix()) {
  Inv <- NULL
  set <- function(y) {
    x <<- y
    Inv <<- NULL
  }
  get <- function() x
  setInverse <- function(Inverse) Inv <<- Inverse
  getInverse <- function() Inv
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## This function uses the "matrix" generated by makeCacheMatrix
# it decides whether the inverse needs to be caculated 
# or retrieved from the internal environment

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  Inv <- x$getInverse()
  if(!is.null(Inv)) {  # check whether Inv exists in the function enviorment
    message("getting Inverse from cached data")
    return(Inv)
  }
  matrix <- x$get()
  Inv <- solve(matrix) # generate the inverse if not there
  x$setInverse(Inv)    # set the intertan environment of the function with the value
  Inv
}

